controller_list:
  - name: fake_arm_controller
    joints:
      - arm1_joint
      - arm2_joint
      - arm3_joint
      - arm4_joint
      - arm5_joint
      - arm6_joint
      - arm7_joint
      - arm8_joint
      - arm9_joint
      - arm10_joint
      - arm11_joint
initial:  # Define initial robot poses.
  - group: arm
    pose: home